/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-dim": "#10131a",
              "on-secondary-fixed": "#00201c",
              "secondary": "#46f5e0",
              "outline-variant": "#494456",
              "on-primary": "#3a0093",
              "on-error": "#690005",
              "surface-container-low": "#191c22",
              "on-secondary-fixed-variant": "#005048",
              "inverse-on-surface": "#2e3037",
              "surface-container-highest": "#32353c",
              "error-container": "#93000a",
              "tertiary": "#ffb1c4",
              "surface-tint": "#cfbdff",
              "surface-container-lowest": "#0b0e14",
              "on-tertiary-container": "#ffb4c6",
              "surface-variant": "#32353c",
              "tertiary-fixed-dim": "#ffb1c4",
              "primary-fixed-dim": "#cfbdff",
              "primary-container": "#6200ee",
              "surface": "#10131a",
              "on-background": "#e1e2eb",
              "on-secondary": "#003731",
              "on-surface-variant": "#cbc3d9",
              "tertiary-container": "#a70051",
              "surface-container": "#1d2026",
              "primary": "#cfbdff",
              "outline": "#948da2",
              "on-tertiary": "#65002e",
              "on-primary-fixed": "#22005d",
              "on-error-container": "#ffdad6",
              "error": "#ffb4ab",
              "surface-container-high": "#272a31",
              "on-surface": "#e1e2eb",
              "on-primary-fixed-variant": "#5300cd",
              "on-tertiary-fixed": "#3f001a",
              "on-secondary-container": "#005950",
              "secondary-container": "#00d8c4",
              "surface-bright": "#363940",
              "primary-fixed": "#e8ddff",
              "inverse-primary": "#6d23f9",
              "on-tertiary-fixed-variant": "#8f0044",
              "on-primary-container": "#d0beff",
              "inverse-surface": "#e1e2eb",
              "secondary-fixed": "#4ffbe6",
              "tertiary-fixed": "#ffd9e1",
              "background": "#10131a",
              "secondary-fixed-dim": "#17deca"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max": "1440px",
              "xs": "4px",
              "gutter": "24px",
              "md": "16px",
              "unit": "4px",
              "xl": "48px",
              "sm": "8px",
              "lg": "24px"
      },
      "fontFamily": {
              "headline-lg": ["Inter", "sans-serif"],
              "code-label": ["JetBrains Mono", "monospace"],
              "display-lg": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "title-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "code-label": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "title-md": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
