/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed": "#002204",
              "error-container": "#93000a",
              "tertiary": "#5cfa69",
              "on-secondary-fixed": "#310048",
              "on-secondary-fixed-variant": "#7200a3",
              "surface-variant": "#323537",
              "on-error-container": "#ffdad6",
              "on-surface-variant": "#D9C3A9",
              "secondary-container": "#630330",
              "on-tertiary": "#00390a",
              "primary-fixed": "#F2E3D2",
              "surface-container": "#1d2022",
              "surface-container-low": "#191c1e",
              "outline": "#D9C3A9",
              "primary": "#F2E3D2",
              "secondary-fixed-dim": "#e9b3ff",
              "on-secondary": "#ffffff",
              "tertiary-fixed": "#70ff76",
              "background": "#101415",
              "on-secondary-container": "#F2E3D2",
              "on-surface": "#F2E3D2",
              "primary-fixed-dim": "#D9C3A9",
              "surface-container-high": "#272a2c",
              "inverse-primary": "#630330",
              "on-tertiary-container": "#005c15",
              "secondary": "#630330",
              "outline-variant": "#3c494e",
              "inverse-surface": "#F2E3D2",
              "on-primary-container": "#101415",
              "inverse-on-surface": "#2d3133",
              "on-primary-fixed": "#001f28",
              "secondary-fixed": "#f6d9ff",
              "tertiary-fixed-dim": "#42e355",
              "error": "#ffb4ab",
              "on-error": "#690005",
              "surface-tint": "#630330",
              "on-primary-fixed-variant": "#004e60",
              "on-primary": "#101415",
              "surface-bright": "#363a3b",
              "surface-dim": "#101415",
              "tertiary-container": "#39dc4f",
              "on-tertiary-fixed-variant": "#005313",
              "surface": "#101415",
              "surface-container-lowest": "#0b0f10",
              "surface-container-highest": "#323537",
              "primary-container": "#F2E3D2",
              "on-background": "#F2E3D2"
      },
      "borderRadius": {
              "DEFAULT": "0.5rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin_desktop": "40px",
              "base_unit": "8px",
              "stack_sm": "8px",
              "margin_mobile": "16px",
              "margin_tablet": "24px",
              "stack_xl": "64px",
              "stack_lg": "32px",
              "container_max_width": "1440px",
              "gutter": "24px",
              "stack_md": "16px"
      },
      "fontFamily": {
              "body-md": ["Inter"],
              "label-caps": ["JetBrains Mono"],
              "headline-md": ["Plus Jakarta Sans"],
              "headline-lg-mobile": ["Plus Jakarta Sans"],
              "headline-lg": ["Plus Jakarta Sans"],
              "code-sm": ["JetBrains Mono"],
              "display-lg": ["Plus Jakarta Sans"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "code-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
