/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-dim": "var(--surface-dim)",
              "on-secondary-fixed": "#00201c",
              "secondary": "#46f5e0",
              "outline-variant": "#494456",
              "on-primary": "#3a0093",
              "on-error": "#690005",
              "surface-container-low": "var(--surface-container-low)",
              "on-secondary-fixed-variant": "#005048",
              "inverse-on-surface": "#2e3037",
              "surface-container-highest": "var(--surface-container-highest)",
              "error-container": "#93000a",
              "tertiary": "#ffb1c4",
              "surface-tint": "#cfbdff",
              "surface-container-lowest": "var(--surface-container-lowest)",
              "on-tertiary-container": "#ffb4c6",
              "surface-variant": "var(--surface-variant)",
              "tertiary-fixed-dim": "#ffb1c4",
              "primary-fixed-dim": "#cfbdff",
              "primary-container": "#6200ee",
              "surface": "var(--surface)",
              "on-background": "var(--on-surface)",
              "on-secondary": "#003731",
              "on-surface-variant": "var(--on-surface-variant)",
              "tertiary-container": "#a70051",
              "surface-container": "var(--surface-container)",
              "primary": "#cfbdff",
              "outline": "#948da2",
              "on-tertiary": "#65002e",
              "on-primary-fixed": "#22005d",
              "on-error-container": "#ffdad6",
              "error": "#ffb4ab",
              "surface-container-high": "var(--surface-container-high)",
              "on-surface": "var(--on-surface)",
              "on-primary-fixed-variant": "#5300cd",
              "on-tertiary-fixed": "#3f001a",
              "on-secondary-container": "#005950",
              "secondary-container": "#00d8c4",
              "surface-bright": "var(--surface-bright)",
              "primary-fixed": "#e8ddff",
              "inverse-primary": "#6d23f9",
              "on-tertiary-fixed-variant": "#8f0044",
              "on-primary-container": "#d0beff",
              "inverse-surface": "var(--on-surface)",
              "secondary-fixed": "#4ffbe6",
              "tertiary-fixed": "#ffd9e1",
              "background": "var(--surface)",
              "secondary-fixed-dim": "#17deca"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max": "1280px",
              "xs": "4px",
              "gutter": "20px",
              "md": "12px",
              "unit": "4px",
              "xl": "40px",
              "sm": "6px",
              "lg": "20px"
      },
      "fontFamily": {
              "changa": ["Changa", "sans-serif"],
              "lemonada": ["Lemonada", "cursive"],
              "readex": ["Readex Pro", "sans-serif"],
              "headline-lg": ["Readex Pro", "sans-serif"],
              "code-label": ["JetBrains Mono", "monospace"],
              "display-lg": ["Changa", "sans-serif"],
              "headline-lg-mobile": ["Readex Pro", "sans-serif"],
              "body-lg": ["Readex Pro", "sans-serif"],
              "body-sm": ["Readex Pro", "sans-serif"],
              "title-md": ["Readex Pro", "sans-serif"]
      },
      "fontSize": {
              "headline-lg": ["28px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "code-label": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.04em", "fontWeight": "500"}],
              "display-lg": ["42px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "800"}],
              "headline-lg-mobile": ["22px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-lg": ["15px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-sm": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "title-md": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
